name: YouTube Data Collector

on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3からv4に更新
        with:
          fetch-depth: 0 # すべての履歴を取得して競合を防ぐ

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add youtube_stats.csv
          # 強制的にリモートの最新状態を取り込んでから、自分の変更を乗せる
          git pull --rebase origin main
          # もし変更があればコミットしてプッシュする
          if ! git diff --cached --exit-code; then
            git commit -m "Update stats"
            git push origin main
          fi
